<a href="https://colab.research.google.com/github/rajeshrockzz/Colab_Files/blob/main/K_Fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://www.kaggle.com/nee2shaji/for-novices-practical-scikit-basics-part-1

# https://github.com/Msanjayds/Scikit-learn/blob/master/CrossValidation.ipynb

https://www.youtube.com/watch?v=2VPn6EBn1v8

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, LeaveOneOut, StratifiedKFold

X = np.ones(10)
y = [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

kf = KFold(n_splits=3)
print("KFold:")
for train, test in kf.split(X):
    print("%s %s" % (train, test))

KFold:
[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [ ]:
from sklearn import datasets
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
import pandas as pd
from sklearn import metrics

In [ ]:
# Load the boston dataset
data = datasets.load_boston()
 
# extract the predictors and target data.
predictors = data.data
target = data.target

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
predictors.shape, target.shape

((506, 13), (506,))

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(predictors,target,test_size = 0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((404, 13), (102, 13), (404,), (102,))

In [ ]:
rf_reg = RandomForestRegressor()
rf_reg.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
y_pred = rf_reg.predict(x_test)

In [ ]:
rsqure_score = rf_reg.score(x_train,y_train)
print('R^2: {}'.format(rsqure_score))

R^2: 0.9808878192868337


In [ ]:
#perform k fold
cv_r2_scores_rf = cross_val_score(rf_reg, predictors, target, cv=5,scoring='r2')
print(cv_r2_scores_rf)
print("Mean 5-Fold R Squared: {}".format(np.mean(cv_r2_scores_rf)))

[0.76945939 0.8546966  0.75552691 0.47881971 0.29695824]
Mean 5-Fold R Squared: 0.631092169761158


In [ ]:
#perform kfold manually
# Load the boston dataset
data = datasets.load_boston()
 
# extract the predictors and target data.
df = pd.DataFrame(data.data)
y =  pd.DataFrame(data.target)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
df.shape,y.shape

((506, 13), (506, 1))

In [ ]:
kf = KFold(n_splits = 5, shuffle = True)
rf_reg = RandomForestRegressor()

In [ ]:
scores = []
for i in range(5):
    result = next(kf.split(df), None)
    x_train = df.iloc[result[0]]
    x_test = df.iloc[result[1]]
    y_train = y.iloc[result[0]]
    y_test = y.iloc[result[1]]
    model = rf_reg.fit(x_train,y_train)
    predictions = rf_reg.predict(x_test)
    scores.append(model.score(x_test,y_test))
print('Scores from each Iteration: ', scores)
print('Average K-Fold Score :' , np.mean(scores))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was pas

Scores from each Iteration:  [0.8782339493189784, 0.7363149295560476, 0.8908938557143831, 0.8901405949089344, 0.9153084945184521]
Average K-Fold Score : 0.8621783648033592


In [ ]:
import pickle
filename = 'final_model.sav'
pickle.dump(rf_reg, open(filename, 'wb'))

In [ ]:
file = open("final_model.sav","rb")
load_model = pickle.load(file)
file.close()

In [ ]:
load_model

RandomForestRegressor()